### PR TITLE
Fix files left unclosed

### PR DESCRIPTION
**Pull request by karthisrinivasan**

### CODE REVIEW

**Review by rmanohar — CHANGES_REQUESTED** [review]
This doesn't need a loop; you can just close the two file descriptors.
```
close (_fd.from);
close (_fd.to);
```

**Comment by karthisrinivasan** [comment]
ah yep, changed :)

**Comment by rmanohar** [comment]
Thanks for finding and fixing this!

**Comment by karthisrinivasan** [comment]
of course!

**Pull request merged**
